name: flutter_projects
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  record: ^5.2.0
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.2.2
  file_picker: ^5.5.0
  just_audio: ^0.9.36
  dio: ^5.0.3
  webview_flutter: ^4.2.2
  provider: ^6.1.1
  flutter_animate: ^4.2.0
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.2.0
  permission_handler: ^11.3.1
  share_plus: ^7.1.0

  #  For authentication
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1

  #  For storage
  firebase_storage: ^11.2.6

  #  For design
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7

  # For PDF viewing
  syncfusion_flutter_pdfviewer: 27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/vexflow.html
    - assets/audio/
    - assets/sounds/piano/
    - assets/soundfonts/