// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmBaY72V4spYzHETbMdYt_O0ShaC2hs64',
    appId: '1:238139794371:web:4ab405f91d37c8a6b79376',
    messagingSenderId: '238139794371',
    projectId: 'wave2notes',
    authDomain: 'wave2notes.firebaseapp.com',
    storageBucket: 'wave2notes.firebasestorage.app',
    measurementId: 'G-8TGN7CDP3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPvQp4ZASUwpBtG3yFCloS6Zl6TufLvxY',
    appId: '1:238139794371:android:d54f87382a9a0cf4b79376',
    messagingSenderId: '238139794371',
    projectId: 'wave2notes',
    storageBucket: 'wave2notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs7M3JY6TA97kKNX2FDV27Tmr-cco3khE',
    appId: '1:238139794371:ios:8559f86b51c49cbcb79376',
    messagingSenderId: '238139794371',
    projectId: 'wave2notes',
    storageBucket: 'wave2notes.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs7M3JY6TA97kKNX2FDV27Tmr-cco3khE',
    appId: '1:238139794371:ios:8559f86b51c49cbcb79376',
    messagingSenderId: '238139794371',
    projectId: 'wave2notes',
    storageBucket: 'wave2notes.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmBaY72V4spYzHETbMdYt_O0ShaC2hs64',
    appId: '1:238139794371:web:610cbeda551f15abb79376',
    messagingSenderId: '238139794371',
    projectId: 'wave2notes',
    authDomain: 'wave2notes.firebaseapp.com',
    storageBucket: 'wave2notes.firebasestorage.app',
    measurementId: 'G-0YHB8C7XNP',
  );
}
